### ISSUE TITLE
1.20.4 Neoforge - Cart will not resume work if there are repair materials present

### ISSUE THREAD

**Issue by Saereth** [CreeperHost/StevesCarts2#28]
If you put for example a stack of diamonds in the repair slot, it will fully repair and then stop working while there are diamond present in the repair slot until you remove them. This presently makes full automation of the carts impossible.

**Comment by brandon3055** [comment]
This mechanic appears to be intentional. There is even a tool tip that lets you know you should remove the extra items when you hover over the durability bar.

My guess is it's intended to help balance the lower tier tools by ensuring the user needs to regularly check and repair them. 

There will be a config option to disable this behaviour in the next version.

**Comment by Saereth** [comment]
The config option works mostly, it will still cut trees and move but it wont plant saplings so I think there may be some other checks ignoring the config

**Comment by brandon3055** [comment]
The wood cutter was attempting to plant the repair item. 
The default logic was just assuming that slot would always be empty, so didn't bother to ignore it.

**Comment by gigabit101** [comment]
should already be fixed, Please re-open if it happens again
